catalogMode: prefer
cleanupUnusedCatalogs: true

publicHoistPattern:
  - "*@rbxts*"

shellEmulator: true

patchedDependencies:
  "@rbxts-js/expect": patches/@rbxts-js__expect.patch
  "@rbxts/jest-globals": patches/@rbxts__jest-globals.patch

catalogs:
  cli:
    bumpp: ^10.4.1
  dev:
    "@rbxts/compiler-types": ^3.0.0-types.0
    "@rbxts/types": ^1.0.906
    "@types/node": ^24.1.0
    file-entry-cache: ^11.1.2
    madge: ^8.0.0
    pncat: ^0.9.1
    roblox-ts: ^3.0.0
  lint:
    "@isentinel/eslint-config": ^4.8.1
    eslint: ^9.39.2
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-jest: ^29.13.0
    eslint_d: ^14.3.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  prod:
    "@rbxts/regexp": ^0.2.1-ts.4
  script:
    jiti: ^2.6.1
  test:
    "@isentinel/jest-roblox": ^0.0.1
    "@rbxts-js/jest-diff": ^3.13.3-ts.3
    "@rbxts/jest": ^3.13.3-ts.1
    "@rbxts/jest-globals": ^3.13.3-ts.1
  tsc:
    "@isentinel/tsconfig": ^1.2.0
    "@typescript/native-preview": ^7.0.0-dev.20260212.1
    get-tsconfig: ^4.13.6
    typescript: ^5.9.3

onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
